site_name: MBOX Converter
site_url: !ENV READTHEDOCS_CANONICAL_URL
site_description: A lightweight tool for converting and processing .mbox files
repo_url: https://github.com/pamagister/mbox_converter
repo_name: GitHub

# See also:
#  https://squidfunk.github.io/mkdocs-material/
#  https://www.mkdocs.org/user-guide/
#  Extensions: https://python-markdown.github.io/extensions/
#  - CodeHilite: https://python-markdown.github.io/extensions/code_hilite/

theme:
  name: readthedocs
  highlightjs: true
  logo: _static/img/logo.jpg
  favicon: _static/img/favicon.png
  features:
    - navigation.instant

extra_css:
  - css/custom.css

markdown_extensions:
  - toc:
      permalink: "#"
  - tables
  - admonition
  - codehilite:
      use_pygments: True

plugins:
   - awesome-nav
