name: Build macOS App

on:
  push:
    tags:
      - '*'  # Triggers for tags like 0.1 or v0.1.3
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11 ]
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Environment # Composite Action
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Executable and App Bundle with PyInstaller
        run: |
          echo "Build of the CLI application"
          uv run pyinstaller --onefile src/python_template_project/cli/cli.py --name executable_cli
          
          echo "Build the GUI application as an .app bundle"
          # --windowed is important to hide the console
          # The name "executable_gui" becomes the name of the .app (executable_gui.app)
          uv run pyinstaller --windowed --name "executable_gui" src/python_template_project/gui/gui.py

      - name: Prepare ZIP file for release
        run: |
          mkdir release
          echo "Copy the CLI file"
          cp dist/executable_cli release/
          echo "Copy the .app bundle (directory) recursively"
          cp -R dist/executable_gui.app release/
          echo "Copy more files"
          cp config.yaml release/
          cp README.md release/
          echo "Create the ZIP archive from the contents of the release folder"
          cd release
          zip -r ../executable_gui-macOS.zip .

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # The file name must match the one created in the previous step
          files: executable_gui-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}