name: Build Windows EXE

on:
  push:
    tags:
      - '*'  # Triggers for tags like 0.1 or v0.1.3
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11 ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Environment # Composite Action
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build EXEs with PyInstaller
        run: |
          echo "Build of the CLI application"
          uv run pyinstaller --onefile src/python_template_project/cli/cli.py --name executable_cli
          
          echo "Build the GUI application with --windowed to hide the console"
          uv run pyinstaller --onefile --windowed src/python_template_project/gui/gui.py --name executable_gui

      - name: Prepare ZIP file for release
        run: |
          mkdir release
          copy dist\executable_cli.exe release\
          copy dist\executable_gui.exe release\
          copy config.yaml release\
          copy README.md release\
          powershell Compress-Archive -Path release\* -DestinationPath installer-win.zip

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # Ensures that the file name matches the one created in the previous step
          files: installer-win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}