name: Build macOS App

on:
  push:
    tags:
      - '*'  # Triggers for tags like 0.1 or v0.1.3
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Environment # Composite Action
        uses: ./.github/actions/setup-environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build macOS CLI Executable with PyInstaller
        run: |
          uv run pyinstaller --onefile src/python-template-project/cli/cli.py --name executable_cli

      - name: Prepare ZIP file for release
        run: |
          mkdir release
          cp dist/executable_cli release/
          cp config.yaml release/
          cp README.md release/
          cd release && zip -r ../installer-macOS.zip *

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: installer-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
